database:
  username: root
  password: 123123
  host: "localhost"
  port: "3306"
  name: "ginprohub_db"
  charset: "utf8mb4"
  loc: "Local"

server:
  ip: "0.0.0.0"
  Port: "8080"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0